Repository bakurits/fileshare, pull requests merged in 2020-10, with the labels that each got.

#1 integriate cobra in fileshare cli app, it has options : list, uploadfile, createdir functions
  LICENSE
  cmd/main.go
  cmd/state.json
  go.mod
  go.sum
  pkg/cmd/customoperations/add.go
  pkg/cmd/drivemanager/authorize.go
  pkg/cmd/drivemanager/createdir.go
  pkg/cmd/drivemanager/list.go
  pkg/cmd/drivemanager/uploadfile.go
  pkg/cmd/root.go
  pkg/terminal/terminal.go
Labels: hacktoberfest-accepted

#2 Fix API design
  pkg/cmd/drivemanager/authorize.go
  pkg/cmd/drivemanager/uploadfile.go
  pkg/drive/drive.go
  pkg/drive/upload.go
Labels: enhancement

#5 Create README.md
  README.md
Labels: documentation
